### ISSUE TITLE
Make this into a VSCode extension?

### ISSUE THREAD

**Issue by Christoph-AK** [scruffystuffs/jfmt.rs#3]
Hey there, I frequently work with large-ish jsons containing product data for e-commerce. 

Sometimes they are formatted in a single line of a few tens of MBs and VSC straight up dies trying to format them.

Sometimes I need to navigate these and would love to do so in VSCode. 

Would it be possible to utilize this formatter for that? 

I didn't find time to look into VSCode extension development yet, but maybe someone around here is already experienced in that.  

Can you even use binaries in extensions, or do they have to be vsc-native JS?

**Comment by skilly-lily** [comment]
It's probably possible, but I'm not going to do it.  But, if someone _else_ wants to use this to make a JSON formatter extension, I'd probably install it.  Btw, vscode extensions can **definitely** use binaries.  

However, for your use-case, I'd recommend running `jfmt` in the command-line, since VScode is ALWAYS going to try to read your file once you open it, and it's going to keep dying the same way.  If you run `jfmt` on the command line, and then open it **after**, vscode can tokenize the file line-by-line, which is likely a big part of the problem you were experiencing.

Since I'm not going to do this, I'm going to close this issue.
